# Generated by Django 4.1.3 on 2022-12-03 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Obraz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tytul', models.CharField(max_length=30, null=True)),
                ('cena', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
