# Generated by Django 4.1.3 on 2022-12-03 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Virtual_Gallery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='obraz',
            name='grafika',
            field=models.ImageField(blank=True, null=True, upload_to='grafiki'),
        ),
    ]
