# Generated by Django 4.1.3 on 2022-12-05 22:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Virtual_Gallery', '0004_alter_obraz_wlasciciel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obraz',
            name='wlasciciel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, unique=True),
        ),
        migrations.CreateModel(
            name='Zamowienie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adres_dostawy', models.CharField(max_length=100, null=True)),
                ('telefon', models.PositiveSmallIntegerField(null=True)),
                ('email', models.CharField(max_length=50, null=True)),
                ('wybrany_obraz', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Virtual_Gallery.obraz')),
                ('zamawiajcy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, unique=True)),
            ],
        ),
    ]
