# Generated by Django 4.1.3 on 2022-12-06 14:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Virtual_Gallery', '0006_alter_obraz_wlasciciel_alter_zamowienie_zamawiajcy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obraz',
            name='wlasciciel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Zamowienie',
        ),
    ]
