# Generated by Django 4.1.3 on 2022-12-09 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Virtual_Gallery', '0007_alter_obraz_wlasciciel_delete_zamowienie'),
    ]

    operations = [
        migrations.AddField(
            model_name='obraz',
            name='opis',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
