# Generated by Django 4.1.3 on 2023-01-13 16:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Virtual_Gallery', '0010_remove_obraz_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wiadomosc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wiadomosc', models.TextField(max_length=200, null=True)),
                ('autor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('obraz', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='Virtual_Gallery.obraz')),
            ],
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
