# Generated by Django 4.1.3 on 2023-01-13 17:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Virtual_Gallery', '0013_alter_wiadomosc_autor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wiadomosc',
            name='autor',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
