# Generated by Django 4.1.3 on 2023-01-14 10:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Virtual_Gallery', '0014_alter_wiadomosc_autor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wiadomosc',
            name='autor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
