# Generated by Django 4.1.3 on 2023-01-14 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Virtual_Gallery', '0015_alter_wiadomosc_autor'),
    ]

    operations = [
        migrations.AddField(
            model_name='wiadomosc',
            name='imie',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
