# Generated by Django 4.1.3 on 2023-01-17 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Virtual_Gallery', '0016_wiadomosc_imie'),
    ]

    operations = [
        migrations.AddField(
            model_name='wiadomosc',
            name='proponowana_cena',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Zaproponuj cenę'),
        ),
        migrations.AddField(
            model_name='wiadomosc',
            name='telefon',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='wiadomosc',
            name='imie',
            field=models.CharField(max_length=20, null=True, verbose_name='Imię'),
        ),
        migrations.AlterField(
            model_name='wiadomosc',
            name='wiadomosc',
            field=models.TextField(max_length=200, null=True, verbose_name='Wiadomość'),
        ),
    ]
